version: '3'
services:

  backend:
    depends_on:
      setup-topology:
        condition: service_completed_successfully

  setup-topology:
    image: pulsarui/setuptopology
    profiles: 
      - demodata
    build:
      context: demodata/setup-topology
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_ADMIN_URL=http://pulsar:8080'
        - 'USE_AWS=false'
    depends_on:
      pulsar:
        condition: service_healthy

  setup-topology-aws:
    image: pulsarui/setuptopology
    profiles: 
      - demodata-aws
    build:
      context: demodata/setup-topology
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_ADMIN_URL=http://pulsar:8080'
        - 'USE_AWS=true'
    depends_on:
      pulsar:
        condition: service_healthy

  demo-producer-consumer:
    image: pulsarui/demoproducerconsumer
    profiles: 
      - demodata
    build:
      context: demodata/demo-producer-consumer
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_URL=pulsar://pulsar:6650'
        - 'PUBLISH_INTERVAL_SECONDS=30'
    depends_on:
      setup-topology:
        condition: service_completed_successfully