version: '3'
services:

  backend:
    image: apachepulsarui/backend
    container_name: backend
    profiles:
      - backend
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - "PULSAR_CONSUMER_URL=pulsar://pulsar:6650"
      - "PULSAR_ADMIN_URL=http://pulsar:8080"
    depends_on:
      pulsar:
        condition: service_healthy

  frontend:
    image: apachepulsarui/frontend
    container_name: frontend
    profiles:
      - frontend
    build:
      context: ./frontend
      args:
        - "BACKEND_URL=http://16.16.200.255:8081"
    ports:
      - "8082:8082"
    depends_on:
      backend:
        condition: service_started

  pulsar:
    image: 'apachepulsar/pulsar:3.0.0'
    ports:
      - '6650:6650'
      - '8080:8080'
    user: '0:0'
    command: sh -c 'bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone'
    environment:
      - 'PULSAR_PREFIX_topicLevelPoliciesEnabled=true'
      - 'PULSAR_PREFIX_systemTopicEnabled=true'
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 10

  setup-topology:
    image: pulsarui/setuptopology
    profiles: 
      - demodata
    build:
      context: demodata/setup-topology
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_ADMIN_URL=http://pulsar:8080'
        - 'USE_AWS=false'
    depends_on:
      pulsar:
        condition: service_healthy
  setup-topology-aws:
    image: pulsarui/setuptopology
    profiles: 
      - demodata-aws
    build:
      context: demodata/setup-topology
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_ADMIN_URL=http://pulsar:8080'
        - 'USE_AWS=true'
    depends_on:
      pulsar:
        condition: service_healthy

  demo-producer-consumer:
    image: pulsarui/demoproducerconsumer
    profiles: 
      - demodata
    build:
      context: demodata/demo-producer-consumer
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_URL=pulsar://pulsar:6650'
        - 'PUBLISH_INTERVAL_SECONDS=30'
    depends_on:
      setup-topology:
        condition: service_completed_successfully
