version: '3'
networks:
  shared-network:
    driver: bridge
services:
  pulsar:
    image: 'apachepulsar/pulsar:2.9.2'
    networks: 
      - shared-network
    ports:
      - '6650:6650'
      - '8080:8080'
    user: '0:0'
    # TODO: need pulsarconf from customer for that to work  (missing config files)
    # they are setting topicLevelPoliciesEnabled=true and systemTopicEnabled=true
    # volumes:
    #   - type: bind
    #     source: demodata/pulsardata
    #     target: /pulsar/data
    #   - type: bind
    #     source: demodata/pulsarconf
    #     target: /pulsar/conf
    command: sh -c 'bin/pulsar standalone'
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 10
  create-topology:
    image: pulsarui/createtopology
    profiles: 
      - init-demodata
    networks:
      - shared-network
    build:
      context: demodata
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_URL=pulsar://pulsar:6650'
    depends_on:
      pulsar:
        condition: service_healthy
  create-customer:
    image: pulsarui/createcustomer
    profiles: 
      - init-demodata
    networks:
      - shared-network
    build:
      context: demodata
      dockerfile: CreateCustomer/Dockerfile
    environment:
        - 'PULSAR_URL=pulsar://pulsar:6650'
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
    depends_on:
      create-topology:
        condition: service_completed_successfully
    
    