version: '3'
networks:
  shared-network:
    driver: bridge
services:
  pulsar:
    image: 'apachepulsar/pulsar:2.11.1'
    networks: 
      - shared-network
    ports:
      - '6650:6650'
      - '8080:8080'
    user: '0:0'
    command: sh -c 'bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone'
    environment:
      - 'PULSAR_PREFIX_topicLevelPoliciesEnabled=true'
      - 'PULSAR_PREFIX_systemTopicEnabled=true'
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 10
  setup-topology:
    image: pulsarui/setuptopology
    profiles: 
      - demodata
    networks:
      - shared-network
    build:
      context: demodata/setup-topology
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_ADMIN_URL=http://pulsar:8080'
    depends_on:
      pulsar:
        condition: service_healthy
  demo-producer-consumer:
    image: pulsarui/demoproducerconsumer
    profiles: 
      - demodata
    networks:
      - shared-network
    build:
      context: demodata/demo-producer-consumer
      dockerfile: Dockerfile
    environment:
        - 'PULSAR_URL=pulsar://host.docker.internal:6650'
        - 'PUBLISH_INTERVAL_SECONDS=30'
    depends_on:
      setup-topology:
        condition: service_completed_successfully
    
    