version: '3'
services:

  backend:
    image: apachepulsarui/backend
    container_name: backend
    profiles:
      - backend
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - "PULSAR_CONSUMER_URL=pulsar://pulsar:6650"
      - "PULSAR_ADMIN_URL=http://pulsar:8080"
      - "FRONTEND_URL=http://${BACKEND_IP}:8082"
    depends_on:
      pulsar:
        condition: service_healthy

  frontend:
    image: apachepulsarui/frontend
    container_name: frontend
    profiles:
      - frontend
    env_file:
      - .env
    build:
      context: ./frontend
      args:
        - "BACKEND_URL=http://${BACKEND_IP}:8081"
    ports:
      - "8082:8082"
    depends_on:
      backend:
        condition: service_started

  pulsar:
    image: 'apachepulsar/pulsar:3.0.0'
    ports:
      - '6650:6650'
      - '8080:8080'
    user: '0:0'
    command: sh -c 'bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone'
    environment:
      - 'PULSAR_PREFIX_topicLevelPoliciesEnabled=true'
      - 'PULSAR_PREFIX_systemTopicEnabled=true'
      - 'PULSAR_PREFIX_brokerDeleteInactiveTopicsEnabled=false'
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 10