name: test-frontend

on: push

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run jest
        run: yarn test --watchAll=false
        working-directory: ./frontend

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run lint
        run: yarn lint
        working-directory: ./frontend
